proxy:
  title: Methods Evaluation and Risk Assessment
  landing-page: /app/slick
  port: 8080 # use Port 8080 for ShinyProxy

  container-wait-time: 60000 # how long should we wait for the container to spin up (30s as default as this is enough for our Shiny apps)
  heartbeat-rate: 10000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 60000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)

  #### Set Up Usage Statistics Monitoring
  usage-stats-url: micrometer # http://influxdb:8086/write?db=shinyproxy_usagestats # use InfluxDB to store usage statistics; can be in a different server
  # usage-stats-username: xxxx # influxdb username if needed
  # usage-stats-password: xxxx # influxdb password if needed

  admin-groups: admins

  #### OpenID Connect Authentication ####
  authentication: none

  # Set the container backend: The container-backend can be one of docker (default), docker-swarm or kubernetes
  container-backend: docker

  docker:
      internal-networking: true

  # Below is a list of Shiny apps and their config
  specs:
    - id: slick
      display-name: Slick
      container-cmd: ["R", "-e", "Slick::Slick(host='0.0.0.0', port=3838)"]
      container-image: adrianrh/slick
      # access-groups: admins # give specific access right to a group
      container-network: sp-net

server:
  forward-headers-strategy: native
  servlet.session.timeout: 0

logging:
  file:
    name: shinyproxy.log

management:
  metrics:
    export:
      prometheus:
        enabled: true
